/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CctvProxy { 
    /**
     * Porta de Comunicação
     */
    port: number;
    /**
     * Nome do Proxy CFTV
     */
    name: string;
    /**
     * Host
     */
    host: string;
    /**
     * ID
     */
    id?: number;
}
