/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface RoleAuthorizeRole { 
    authorizerRole?: Role;
    authorizedRole?: Role;
    /**
     * ID
     */
    id?: number;
}
