/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Timezone { 
    /**
     * Offset em Minutos do Timezone
     */
    timezoneOffset?: number;
    /**
     * Nome do Timezone
     */
    name?: string;
    /**
     * ID
     */
    id?: number;
}
