/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallGenerationType } from './callGenerationType';
import { Device } from './device';
import { VirtualLobby } from './virtualLobby';
import { VirtualLobbyAction } from './virtualLobbyAction';


export interface VirtualLobbyDevice { 
    virtualLobby?: VirtualLobby;
    virtualLobbyAction: VirtualLobbyAction;
    /**
     * ID
     */
    id?: number;
    device: Device;
    callGenerationType: CallGenerationType;
}
