/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type VirtualLobbyActionType = 'DISABLE_ACTION' | 'ENABLE_ACTION' | 'ENABLE_ACTION_WITH_TIMEOUT';

export const VirtualLobbyActionType = {
    DISABLEACTION: 'DISABLE_ACTION' as VirtualLobbyActionType,
    ENABLEACTION: 'ENABLE_ACTION' as VirtualLobbyActionType,
    ENABLEACTIONWITHTIMEOUT: 'ENABLE_ACTION_WITH_TIMEOUT' as VirtualLobbyActionType
};
